### ISSUE TITLE
New directories are not observed by gwatchd

### ISSUE THREAD

**Issue by szymonskirgajllo** [gorzechowski/gwatchd#5]
1) Remove whole directory (with commit = another branch)
b) git add . && git commit -m 'remove test directory' && git push origin new_branch
2) Run gwatchd
3) Switch to a branch which contains removed directory
a) git checkout old_branch
4) Gwatchd omits removed directory

it is clear?

**Comment by gorzechowski** [comment]
While using GWatchd I noticed it too, that in few situations watchers are not added. It's bug.
